### PR TITLE
Voting changes

### PR DESCRIPTION
**Pull request by scarbunkle**
Several independent Amendments:
1. Add clarifying language re: interim appointments and half-monsters.
2. Delete Quiet Hours.  RP controls these, I believe.
3. Delete Rocky SAFC--They can't postallocate, and are not a student group right now.
4. Allow evoting on an election-by-election basis with 2/3rds Kommittee approval of the system used.  Keep a booth with during these elections to remind people.  Change wording to permit this.
5. Multiple choice to instant runoff rather than having a second runoff vote.

### CODE REVIEW

**Comment by scarbunkle** [comment]
Needs to go to referendum for 2-5.  Referendum approved by Kommittee.

**Comment by chrisbrickhouse** [comment]
I will work on closing this ticket

**Comment by scarbunkle** [comment]
Thanks.  Also, do you want ownership permissions for the master? It seems appropriate to have a non alumna maintainer.

**Comment by chrisbrickhouse** [comment]
Kommittee is working on figuring that out, but I doubt people will object to me having write access until we come to a solution.

**Comment by chrisbrickhouse** [comment]
Resolved by Commit #35

**Pull request closed without merging**
